no18/web_test_bigio/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'LoginController@index');
Route::get('/login', 'LoginController@index')->name('login');
Route::post('/login', 'LoginController@do_login')->name('logins.login');
Route::get('/logout', 'LoginController@do_logout')->name('logins.logout');
Route::resource('home','DashboardController');
Route::get('/guru','GuruController@index');
Route::get('/guru/create','GuruController@create');
Route::post('/guru/store','GuruController@store');
Route::get('/guru/edit/{id}','GuruController@edit');
Route::patch('/guru/update/{id}','GuruController@update');
Route::get('/guru/show/{id}','GuruController@show');
Route::delete('/guru/delete', 'GuruController@destroy');
Route::get('/murid','MuridController@index');
Route::get('/murid/create','MuridController@create');
Route::post('/murid/store','MuridController@store');
Route::get('/murid/edit/{id}','MuridController@edit');
Route::patch('/murid/update/{id}','MuridController@update');
Route::get('/murid/show/{id}','MuridController@show');
Route::delete('/murid/delete', 'MuridController@destroy');
Route::get('/nilaimurid','NilaiMuridController@index');
Route::get('/nilaimurid/create','NilaiMuridController@create');
Route::post('/nilaimurid/store','NilaiMuridController@store');
Route::get('/nilaimurid/edit/{id}','NilaiMuridController@edit');
Route::patch('/nilaimurid/update/{id}','NilaiMuridController@update');
Route::get('/nilaimurid/show/{id}','NilaiMuridController@show');
Route::delete('/nilaimurid/delete', 'NilaiMuridController@destroy');
Route::get('/lihatnilaimurid/{id}','NilaiMuridController@showNilaiPerMurid');

no18/web_test_bigio/resources/views/pages/lihatnilaimurid/index.blade.php
  @extends('layouts.index')

  @section('title','Data Nilai')

  @section('container')
    <div class="container-fluid">
        <h5 class="title-page pt-3">Data Nilai</h5>
        <nav class="breadcrumb-nav" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <p>Data Nilai</p>
                <li class="breadcrumb-item active"><a href="{{route('home.index')}}">Home</a></li>
                <li class="breadcrumb-item" aria-current="page">Data Nilai</li>
            </ol>
        </nav>

        <div class="card show-card">
            <!-- START HEADER -->
            <div class="card-header">
                <div class="row">
                    <div class="col-6 mt-1">
                        <strong> Data Nilai</strong>
                    </div>
                </div>    
            </div>
            <!-- END HEADER -->
            <div class="card-body">
                <table class="table table-borderless">
                    <tr>
                        <td>Nama</td>
                        <td>{{$murid->nama}}</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Kelas</td>
                        <td>{{$murid->kelas}}</td>
                        <td></td>
                    </tr>
                </table>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Mata Pelajaran</th>
                            <th scope="col">Nilai</th>   
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($nilaimurids as $nilaimurid)
                        <tr>
                            <th scope="row">{{$loop->iteration+$nilaimurids->firstItem()-1}}</th>
                            <td>{{$nilaimurid->mata_pelajaran}}</td>
                            <td>{{number_format($nilaimurid->nilai, 0, ',', '.')}}</td>
                        <tr>
                        @empty
                        <tr>
                            <td colspan="6" class="text-center p-5">
                                Data tidak tersedia
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                 <!-- PAGINATION -->
                 <div class="row">
                    <div class="col-sm-4">
                        <p class="text-sm-start fs-6 fw-bold">Halaman {{$nilaimurids->currentPage()}} dari {{$nilaimurids->lastPage()}} | Data {{$nilaimurids->firstItem()}}-{{$nilaimurids->lastItem()}} dari total {{$nilaimurids->total()}}</p>
                    </div>
                    <div class="col-sm-8">
                        <nav aria-label="...">
                            <ul class="pagination d-flex justify-content-end">
                                <li class="page-item {{$nilaimurids->currentPage() == $nilaimurids->onFirstPage() ? 'disabled': ''}}">
                                    <a class="page-link" href="{{$nilaimurids->url($nilaimurids->onFirstPage())}}" id="FirstPage">Previous</a>
                                </li>
                                {{$nilaimurids->appends(Request::all())->onEachSide(1)->links()}}
                                <li class="page-item {{$nilaimurids->currentPage() == $nilaimurids->lastPage() ? 'disabled': ''}}">
                                    <a class="page-link" href="{{$nilaimurids->url($nilaimurids->lastpage())}}" id="LastPage">Last</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- END PAGINATION  -->
            </div>
        </div>
    </div>

    
  @endsection

no18/web_test_bigio/resources/views/pages/lihatnilaimurid/show.blade.php
<section>
                        <div class="row">
                            <!-- ALAMAT TAGIHAN -->
                            <div class="col-sm-6">
                                <div class="card card-address">
                                    <div class="card-header">
                                        <strong>Alamat Tagihan</strong>   
                                    </div>
                                    <div class="card-body">
                                        <p class='card-text'>{{$transaction->SenderName}} | {{$transaction->SenderPhoneNumber}}</p>
                                        <p class='card-text'>{{$transaction->SenderAddress}}</p>
                                        <p class='card-text'>{{$transaction->SenderCity}} {{$transaction->SenderProvince}} {{$transaction->SenderPostalCode}}</p>
                                    </div>
                                </div>
                            </div>
                            <!-- END ALAMAT TAGIHAN -->
                            
                            <!-- ALAMAT PENGIRIMAN -->
                            <div class="col-sm-6">
                                <div class="card card-address">
                                    <div class="card-header">
                                        <strong>Alamat Pengiriman</strong>   
                                    </div>
                                    <div class="card-body">
                                        <p class='card-text'>{{$transaction->ReceiverName}} | {{$transaction->ReceiverPhoneNumber}}</p>
                                        <p class='card-text'>{{$transaction->ReceiverAddress}}</p>
                                        <p class='card-text'>{{$transaction->ReceiverCity}} {{$transaction->ReceiverProvince}} {{$transaction->ReceiverPostalCode}}</p>
                                    </div>
                                </div>
                            </div>
                            <!-- END ALAMAT PENGIRIMAN -->
                        </div> 
                    </section>
                    <div class="card card-detail-order mt-2">
                        <div class="card-header">
                            <strong>Detail Pesanan</strong>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Barang</th>
                                        <th scope="col">Kuantiti</th>
                                        <th scope="col">Harga</th>
                                        <th scope="col">Subtotal</th>     
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $totalSubtotal=0 @endphp
                                        @foreach($transaction->transaction_item as $transaction_detail)
                                            <tr>
                                                <td>{{$transaction_detail->name}}</td>
                                                <td>{{$transaction_detail->qty}}</td>
                                                <td>Rp.{{number_format($transaction_detail->totalprice, 0, ',', '.')}}</td>
                                                <td>Rp.{{number_format(($transaction_detail->total), 0, ',', '.')}}</td>
                                                @php $totalSubtotal+=$transaction_detail->total @endphp
                                            <tr>
                                        @endforeach
                                            <tr class="noBorder">
                                                <td colspan="3"><b class="fw-bold">TOTAL</b></td>

                                                <td><b class="fw-bold">Rp.{{number_format($totalSubtotal, 0, ',', '.')}}</b></td>
                                            </tr>
                                            <tr class="noBorder">
                                                <td colspan="3"><b class="fw-bold">PAJAK(10%)</b></td>
                                                @php $totalPajak=($totalSubtotal*(10/100)) @endphp
                                                <td><b class="fw-bold">Rp.{{number_format($totalPajak, 0, ',', '.')}}</b></td>
                                            </tr>
                                            <tr class="noBorder">
                                                <td colspan="3"><b class="fw-bold">ONGKOS KIRIM</b></td>
                                                <td><b class="fw-bold">Rp.{{number_format($transaction->shipping_price, 0, ',', '.')}}</b></td>
                                            </tr>
                                            <tr class="noBorder">
                                                <td colspan="3"><b class="fw-bold">GRANDTOTAL</b></td>
                                                <td><b class="fw-bold">Rp.{{number_format(($totalSubtotal+$totalPajak+$transaction->shipping_price), 0, ',', '.')}}</b></td>
                                            </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @if($transaction->payment_status=='LUNAS' && $transaction->transaction_status=='KONFIRMASI PEMBAYARAN')
                    <div class="row mt-3">
                        <div class="col-4">
                            <a href="{{route('transactions.status',$transaction->id)}}?status=DIKIRIM" class="btn btn-warning btn-block">
                                <i class="fas fa-shipping-fast"></i> Set Dikirim
                            </a>
                        </div>
                    </div>
                    @else
                    <div class="row mt-3">
                        <div class="col-4">
                            <a href="#" class="btn btn-warning btn-block disabled">
                                <i class="fas fa-shipping-fast"></i> Set Dikirim
                            </a>
                        </div>
                    </div>
                    @endif    